In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(
    "../data/online_retail_II.xlsx",
    sheet_name="Year 2010-2011"
)

print(df.shape)

(541910, 8)

In [3]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64

In [4]:
df = df.dropna(subset=["Customer ID"])

print(df.shape)

(406830, 8)

In [5]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 5225

In [6]:
df = df.drop_duplicates()

print(df.shape)

(401605, 8)

In [7]:
(df["Quantity"] < 0).sum()

np.int64(8872)

In [8]:
df = df[df["Quantity"] > 0]

print(df.shape)

(392733, 8)

In [9]:
(df["Price"] <= 0).sum()

np.int64(40)

In [10]:
df = df[df["Price"] > 0]

print(df.shape)

(392693, 8)

In [11]:
df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"]
)

In [12]:
df["TotalAmount"] = (
    df["Quantity"] *
    df["Price"]
)

In [13]:
df[["Quantity","Price","TotalAmount"]].head()

   Quantity  Price  TotalAmount
0         6   2.55        15.30
1         6   3.39        20.34
2         8   2.75        22.00
3         6   3.39        20.34
4         6   3.39        20.34

In [14]:
df["Year"] = df["InvoiceDate"].dt.year

In [15]:
df["Month"] = df["InvoiceDate"].dt.month

In [16]:
df["Day"] = df["InvoiceDate"].dt.day

In [17]:
df["Weekday"] = (
    df["InvoiceDate"]
    .dt.day_name()
)

In [18]:
df["Quarter"] = (
    df["InvoiceDate"]
    .dt.quarter
)

In [19]:
df["CustomerFrequency"] = (
    df.groupby("Customer ID")
      ["Invoice"]
      .transform("count")
)

In [20]:
def order_size(amount):

    if amount < 50:
        return "Small"

    elif amount < 200:
        return "Medium"

    else:
        return "Large"

df["OrderSize"] = (
    df["TotalAmount"]
    .apply(order_size)
)

In [21]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalAmount,Year,Month,Day,Weekday,Quarter,CustomerFrequency,OrderSize
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,1,Wednesday,4,297,Small
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,Wednesday,4,297,Small
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,1,Wednesday,4,297,Small
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,Wednesday,4,297,Small
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,Wednesday,4,297,Small

In [22]:
df.to_csv(
    "../data/cleaned_retail.csv",
    index=False
)

print("Dataset Saved")

Dataset Saved

In [23]:
print(df.shape)

(392693, 16)